### ISSUE TITLE
Compilation failure on OSX

### ISSUE THREAD

**Issue by stephanmg** [UG4/ugcore#38]
See the Travis build (STATIC_BUILD=OFF and TARGET=vrl this corresponds to build2 and build4):

https://travis-ci.org/github/UG4/ugcore/jobs/729465313

`/Users/travis/build/UG4/ugcore/travis_root/ug4/ugcore/ugbase/common/stopwatch.h:53:10: fatal error: 'chrono' file not found
#include <chrono>`

Looks like in these cases (`--with-gxx-include-dir=/usr/include/c++/4.2.1`) which has not the C++11 headers available. Can someone confirm?

Note: 
When using `-stdlib=libc++` then the `libc++ `standard library is included, instead of the `gnu libstdc++`. On OS X, the `libc++ `version has c++11 support. The `gnu libstdc++` one does not. (At least to my knowledge)

**Comment by mlampe** [comment]
The combo gcc/osx tests the "gcc" supplied by MacOS. This "gcc" is actually clang using c++ headers and lib from gcc 4.2.1.
But half of the clang/osx tests (using clang with or without `-stdlib=libc++`) also fail because the 'crono' header file is not found: [https://travis-ci.org/github/UG4/ugcore/builds/728486378]

**Comment by stephanmg** [comment]
@mlampe: How about this in (.travis.yml)?

` - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="-stdlib=libc++"; fi`

**Comment by mlampe** [comment]
As I said above: The two OSX Travis builds with CC=clang and TARGET=vrl fail either way. The 'chrono' header is not found.
